import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import SearchBar from "~/components/SearchBar";
import { useState } from "react";
import WeatherViewport, { IWeather } from "~/components/WeatherViewport";
import { ViewController } from "~/components/viewport/weather/view/Controller";

export default function Home() {
  const [weather, setWeather] = useState<IWeather | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [background, setBackground] = useState('bg-gradient-to-t from-sky-500 to-blue-500')
  const updateSearch = (props: IWeather) => {
    setWeather(props);
    setBackground(ViewController({props}));
    setIsLoading(false);
  }
  const setLoading = () => {
    setIsLoading(true);
    
  }

  return (
    <>
      <Head>
        <title>Weather</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`w-full h-screen ${background} `}>
        <SearchBar updateSearch={updateSearch} setLoading={setLoading}/>
        {weather && <WeatherViewport props={weather} loading={isLoading}/>}
      </main>
    </>
  );
}
